import yaml

# Load the settings from the YAML file
with open('settings.yaml', 'r') as yaml_file:
    settings = yaml.safe_load(yaml_file)

# Assign constants from the settings
SIZE_BOARD = settings['SIZE_BOARD']
NUMBER_OF_LINES_OF_DOTS_IN_START = settings['NUMBER_OF_LINES_OF_DOTS_IN_START']
PLAYER_1_COLOR = tuple(settings['PLAYER_1_COLOR'])
PLAYER_2_COLOR = tuple(settings['PLAYER_2_COLOR'])
PORT = settings['PORT']
IP_ADDRESS_SERVER = settings['IP_ADDRESS_SERVER']
IP_ADDRESS_CLIENT = settings['IP_ADDRESS_CLIENT']

WIDTH = 1500
HEIGHT = 800
WHITE = (255, 255, 255)
GREY = (112, 112, 112)
BLACK = (0, 0, 0)
BROWN = (150, 75, 0)
RED = (255, 0, 0)
MARGIN = 60
BOARD_LINE_WIDTH = 3
BOARD_COLOR = BLACK
PLAYER_1_COLOR_SELECTED = (153, 204, 255)
PLAYER_2_COLOR_SELECTED = (255, 153, 253)
UP_DIRECTION = "UP"
DOWN_DIRECTION = "DOWN"
PLAYER_1_DIRECTION = UP_DIRECTION
PLAYER_2_DIRECTION = DOWN_DIRECTION
CROWN_PATH = "assets\\images\\crown.png"

UP_LEFT = (MARGIN, MARGIN)
DOWN_RIGHT = (min(WIDTH, HEIGHT) - MARGIN, min(WIDTH, HEIGHT) - MARGIN)
SQUARE_SIZE = (DOWN_RIGHT[0] - UP_LEFT[0]) / SIZE_BOARD
